[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Technology"
  url = "categories/technology/"
  weight = -109

# Sub-menus are done this way: parent -> identifier
#[[main]]
#  name = "Links"
#  identifier = "Links"
#  weight = -108
#[[main]]
#  parent = "Links"
#  name = "LinkedIn"
#  url = "https://www.linkedin.com/"
#[[main]]
#  parent = "Links"
#  name = "Twitter"
#  url = "https://twitter.com/"

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/rchamarthy"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/ravinag"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/ravinag"
[[social]]
  name = "stackoverflow"
  weight = 4
  url = "https://stackoverflow.com/users/973796/ravi-chamarthy"
[[social]]
  name = "rss"
  weight = 5
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"